name: CICD

on: [push]

jobs:
  ci:
  #  build-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
        - uses: php-actions/composer@v6
        - run: echo "Composer dependencies have been installed"
        - run: vendor/bin/phpunit tests/
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v3
  #    - name: Docker Login
  #      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
  #    - name: Build
  #      run: |
  #        docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }} .
  #        docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:latest .
  #    - name: Push
  #      run: |
  #        docker push ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }}
  #        docker push ${{ secrets.DOCKER_USER }}/numerocicd:latest